export { EnveMemory, type OpenOptions } from './memory.ts';
export { MemoryError, type MemoryErrorCode } from './errors.ts';
export { cacheDir, defaultHome, pathsFor, type MemoryPaths } from './paths.ts';
export { migrate, openDatabase, schemaVersion, transaction } from './db.ts';
export { MIGRATIONS, type Migration } from './migrations.ts';
export { toFtsQuery } from './search.ts';
export { normalizeTag } from './context.ts';
export { type Embedder, type VectorHit, chunkText } from './embeddings.ts';
export { MAX_LIMIT } from './items.ts';
export type { ItemFilter, SaveLinkInput, SaveNoteInput, SourceUpdate, UpdateItemInput } from './items.ts';
export { EXTRACTABLE_TYPES, type SaveFileInput } from './files.ts';
export { isPlainText, mimeFor } from './mime.ts';
export type { CreateTaskInput, TaskListStatus, UpdateTaskInput } from './tasks.ts';
export type { CreateProjectInput, UpdateProjectInput } from './projects.ts';
export type { RecordDecisionInput } from './decisions.ts';
export type { Settings } from './settings.ts';
export { DrainWorker } from './worker.ts';
export { EXPORT_FORMAT, EXPORT_VERSION, type ExportSummary } from './export.ts';
export { BACKUP_KINDS, type Backup, type BackupKind, listBackups, restoreBackup, verifyBackup } from './backups.ts';
export * from './types.ts';
